### ISSUE TITLE
How to use multi touch boards as midi devices on one Mac/PC ?

### ISSUE THREAD

**Issue by LuZhouheng** [BareConductive/generic-usb-midi-interface#1]
Hi, @stefandz @loosepascal @mattmjohnson @bareconductiverobot 

I follow the tutorial to build midi device using touch board, but when i plug 2 touch boards as my midi controllers. The software can recognize only one touch board. 

Is it possible to do that? like the "multi-board-touch-midi" project by BareConductive ?

=> In Touch Designer (software), It can be recognized as 2 devices

<img width="1187" alt="ead01de1-8eff-4ade-a601-7df35abffe15" src="https://user-images.githubusercontent.com/14038819/33062133-2e0d89ae-ced9-11e7-99ce-7cb6510c69b0.png">

=> But only one board can sending data to computer, and it sending double data by only one touch

<img width="1160" alt="ce027428-3e1e-4718-acff-0938b06f44d9" src="https://user-images.githubusercontent.com/14038819/33062092-0d757eae-ced9-11e7-80b7-574290c251ff.png">

Hope for your reply, thanks very much

**Comment by stefandz** [comment]
Hi

For each `MIDI_NOTE` or `MIDI_CONTROL` object you should ensure that the assigned `noteNumber` or `controllerNumber` in lines [66-263](https://github.com/BareConductive/generic-usb-midi-interface/blob/public/Midi_interface_generic/Midi_interface_generic.ino#L66-L263) is different for each board. This should avoid the collisions you are seeing.

Alternatively you can modify line [292](https://github.com/BareConductive/generic-usb-midi-interface/blob/public/Midi_interface_generic/Midi_interface_generic.ino#L292), [297](https://github.com/BareConductive/generic-usb-midi-interface/blob/public/Midi_interface_generic/Midi_interface_generic.ino#L297) and [328](https://github.com/BareConductive/generic-usb-midi-interface/blob/public/Midi_interface_generic/Midi_interface_generic.ino#L328) to alter the channel number. Currently these set `e.m1` to `0x90`, `0x80` and `0xB0` respectively. The last 4 bits of each of these bytes is the channel number - currently set to 0. If you set these to `0x91`, `0x80`, `0xB1` you set the board to channel 1, `0x92`, `0x82`, `0xB2` sets the board to channel 2 and so on up to `0x9F`, `0x8F`, `0xBF` (channel 15). We will hopefully push a code change out soon for this which will make channel changes a little bit less tricky!

Have fun!

S

**Comment by LuZhouheng** [comment]
Hi

I have tried to change ``` Serial.begin(9600);```, one board set to ```MIDI_NOTE```, the other set to ```MIDI_CONTROL```, and alter the ```e.m1``` to different channel.

but i still got only one board connected, both in Touch Designer and Madmapper.

btw, I use one board by MIDI and another set to "Data Stream" and sending data by OSC via Max/Msp. Then I got 2 board connected.

<img width="1641" alt="a5bafabe-bb15-493d-9e2c-ba677a6fd67e" src="https://user-images.githubusercontent.com/14038819/33201661-6f845fae-d134-11e7-9a88-8b472a9a099e.png">

**Comment by stefandz** [comment]
Hi

Not sure why you are changing `Serial.begin(9600)` - this won't affect anything that you are seeing. You may well still see only one board (as it has only one VID / PID and we don't set board serial numbers) but by setting `e.m1` to a different channel you will be able to tell which note or control events came from which board. So you will still see 1 board, but you will be able to differentiate between the signals coming from multiple boards.

Hope that makes sense - let me know if you are still struggling.

All the best

S

**Comment by stefandz** [comment]
Hi

Not sure why you are changing `Serial.begin(9600)` - this won't affect anything that you are seeing. You may well still see only one board (as it has only one VID / PID and we don't set board serial numbers) but by setting `e.m1` to a different channel you will be able to tell which note or control events came from which board. So you will still see 1 board, but you will be able to differentiate between the signals coming from multiple boards.

Hope that makes sense - let me know if you are still struggling.

All the best

S

**Comment by loosepascal** [comment]
Hey @LuZhouheng,

Were you able to solve this issue?

Best,

Pascal
